---
# shared playbook for bitbucket setup

- hosts: bitbucket
  remote_user: root
  roles:
    - bitbucket
    - { role: mysql_connector_java, mysql_connector_java_dest: "{{ bitbucket_catalina }}/lib" }
